/* DO NOT EDIT THIS FILE - it is machine generated
 * 用来画任何东西的头文件
 * */
#pragma once

#include "sggl.h"
#include "vertexbuffer.h"
#include "shader.h"
class Circle {
public:
    //修改以前的 MVP ,都有自己来维护
    SShader *mShader;
    VertexBuffer *vertexBuffer;
    glm::mat4 mModelMatrix;
    glm::mat4 mViewMatrix;
    glm::mat4 mProjectionMatrix;

public:
    void initVertex(float x, float y, float z,int count );//初始化数据
    void initMVP( float width,float height,glm::vec3 carmeaPos);
    void draw();
};






