/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_openglcamera_natives_NativeOpencvOpstion */

#ifndef _Included_sen_com_openglcamera_natives_NativeOpencvOpstion
#define _Included_sen_com_openglcamera_natives_NativeOpencvOpstion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_openglcamera_natives_NativeOpencvOpstion
 * Method:    saveBitmap
 * Signature: ([B)[B
 */
JNIEXPORT void JNICALL Java_sen_com_openglcamera_natives_NativeOpencvOpstion_saveBitmap
  (JNIEnv *, jclass,  jobject );

 JNIEXPORT void JNICALL Java_org_opencv_android_Utils_nBitmapToMat2
        (JNIEnv *, jclass, jobject , jlong , jboolean );
 JNIEXPORT void JNICALL Java_org_opencv_android_Utils_nMatToBitmap
        (JNIEnv *, jclass, jlong , jobject );



JNIEXPORT void JNICALL Java_sen_com_openglcamera_natives_NativeOpencvOpstion_saveBitmapByData(JNIEnv *, jclass ,
                                                                       jbyteArray , jint ,
                                                                       jint ) ;
#ifdef __cplusplus
}
#endif
#endif
