/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_openglcamera_mediacodec_NativeSwapYUV */

#ifndef _Included_sen_com_openglcamera_mediacodec_NativeSwapYUV
#define _Included_sen_com_openglcamera_mediacodec_NativeSwapYUV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_openglcamera_mediacodec_NativeSwapYUV
 * Method:    swapYUV
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_sen_com_openglcamera_natives_NativeSwapYUV_nV21ToI420
  (JNIEnv *, jclass, jbyteArray,jint,jint,jint);

JNIEXPORT jbyteArray JNICALL Java_sen_com_openglcamera_natives_NativeSwapYUV_yV12ToI420
        (JNIEnv *, jclass, jbyteArray,jint,jint,jint);

#ifdef __cplusplus
}
#endif
#endif
