/* DO NOT EDIT THIS FILE - it is machine generated */
/**
 * 防第三方库，加入一些需要的头，用起来比较方便
 */
#pragma once
#include <jni.h>
#include "android/asset_manager.h"
#include "android/asset_manager_jni.h"
#include "GLES2/gl2.h"
#include "GLES2/gl2ext.h"
#include <stdio.h>
#include <math.h>
//c++
#include <string>
//c
#include <string.h>
//c++ 的流
#include <sstream>
//容器
#include <vector>
#include <functional>
#include <map>
#include "Glm/glm.hpp"
#include "Glm/ext.hpp"
#include "android/log.h"
#define LOG_TAG    "sen_"
#define LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG, __VA_ARGS__)

