/* DO NOT EDIT THIS FILE - it is machine generated
 * 加载文件的工具
 * */
#pragma once

#include "sggl.h"
struct Vertex{
    float position[4];
    float color[4];
    float texcoord[4]; //贴图坐标
    float normal[4]; //法向
};

class VertexBuffer{
public:
    Vertex *mVertexes; //先定义指针
    int mVertexCount; //数组的大小
    GLuint mVbo;
    void setSize(int vertexSize);
    void setPosition(int index,float x,float y,float z, float w =1.0f);
    void setColor(int index,float r,float g,float b ,float a=1.0f);
    void setTexcoord(int index,float x,float y);
    void setNarmal(int index ,float x,float y,float z);
    //执行该函数时，才将cpu 数据上传gpu
    void bind();
    void unBind();
    Vertex &get(int index); //这个可以修改某个数据
};






